-- V1: schema  (generated from AmigoWalletMySql.sql during 2026 modernization)
--
-- Faithful reproduction of the original CREATE TABLE / ALTER TABLE DDL, with ONLY:
--   * the `drop database` / `create database` / `use` header removed (the MySQL
--     container + Spring datasource own the database; migrations must not switch DBs);
--   * charset converted from latin1 / latin1_general_cs to utf8mb4 / utf8mb4_unicode_ci
--     (applied table-level as `DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
--     since the original set it at the database level in the now-removed header).
-- Column types (FLOAT/INT/BIGINT/VARCHAR/CHAR), PKs, UNIQUE, CHECK, AUTO_INCREMENT,
-- and DEFAULT CURRENT_TIMESTAMP are preserved EXACTLY as the source had them.

CREATE TABLE WALLET_USER(
	USER_ID INT(6) NOT NULL AUTO_INCREMENT,
	EMAIL_ID VARCHAR(255) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	USER_STATUS VARCHAR(10) NOT NULL, --  'ACTIVE', 'INACTIVE'
	SECURITY_QUESTION_ID BIGINT(10),
	SECURITY_ANSWER VARCHAR(100),
	CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	constraint AW_WALLET_USER_ID_PK primary key (USER_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE BANK(
	BANK_ID INT(3) NOT NULL,
	BANK_NAME VARCHAR(50) NOT NULL,
	constraint EW_BANK_ID_PK primary key (BANK_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CARD(
	CARD_ID INT(6) AUTO_INCREMENT,
	CARD_NUMBER VARCHAR(16),
	BANK_ID INT(3) NOT NULL,
	EXPIRY_DATE DATE NOT NULL,
	CARD_STATUS VARCHAR(10) NOT NULL, --  'ACTIVE', 'INACTIVE'
	CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_ID INT(6),
	constraint EW_USER_CARD_ID_PK primary key (CARD_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- LEGACY redundant table: no JPA entity maps USER_CARD_MAPPING. Kept for schema
-- fidelity with the original script; the CARD.USER_ID FK column supersedes it.
CREATE TABLE USER_CARD_MAPPING(
	USER_ID INT(6),
	CARD_ID INT(6),
	constraint EW_USER_CARD_USER_ID_UNQ UNIQUE (USER_ID, CARD_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MERCHANT(
	MERCHANT_ID INT(4),
	EMAIL_ID VARCHAR(255) UNIQUE NOT NULL,
	MOBILE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	MERCHANT_STATUS VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL, --  'ACTIVE', 'INACTIVE'
	CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	constraint EW_MERCHANT_ID_PK primary key (MERCHANT_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MERCHANT_SERVICE_TYPE(
	SERVICE_ID INT(3) AUTO_INCREMENT,
	SERVICE_TYPE VARCHAR(50) UNIQUE NOT NULL,
	constraint EW_MERCHANT_SERVICE_TYPE_ID_PK primary key (SERVICE_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MERCHANT_SERVICE_MAPPING(
	MERCHANT_ID INT(4) NOT NULL,
	SERVICE_ID INT(3) NOT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE PAYMENT_TYPE(
	PAYMENT_TYPE_ID INT(3),
	PAYMENT_FROM CHAR(1) NOT NULL,
	PAYMENT_TO CHAR(1) NOT NULL,
	PAYMENT_TYPE CHAR(1) NOT NULL,
	constraint EW_PAYMENT_TYPE_ID_PK primary key (PAYMENT_TYPE_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE USER_TRANSACTION(
	USER_TRANSACTION_ID BIGINT(10) AUTO_INCREMENT,
	AMOUNT FLOAT(12,2) NOT NULL,
	TRANSACTION_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PAYMENT_TYPE_ID INT(3) NOT NULL,
	REMARKS VARCHAR(50),
	INFO VARCHAR(100) NOT NULL,
	TRANSACTION_STATUS VARCHAR(10) NOT NULL,
	POINTS_EARNED INT(5) DEFAULT 0 NOT NULL,
	IS_REDEEMED CHAR(1) DEFAULT 'N' NOT NULL,
	USER_ID INT(6),
	constraint EW_USER_TRANSACTION_ID_PK primary key (USER_TRANSACTION_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- LEGACY redundant table: no JPA entity maps USER_TRANSACTION_MAPPING. Kept for schema
-- fidelity with the original script; the USER_TRANSACTION.USER_ID FK column supersedes it.
CREATE TABLE USER_TRANSACTION_MAPPING(
	USER_TRANSACTION_ID BIGINT(10) NOT NULL,
	USER_ID INT(6) NOT NULL,
	constraint EW_USER_TXN_ID_USER_ID_UNQ UNIQUE (USER_TRANSACTION_ID, USER_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE MERCHANT_TRANSACTION(
	MERCHANT_TRANSACTION_ID BIGINT(10) AUTO_INCREMENT,
	AMOUNT FLOAT(12,2) NOT NULL,
	TRANSACTION_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PAYMENT_TYPE_ID INT(3) NOT NULL,
	REMARKS VARCHAR(50),
	INFO VARCHAR(100) NOT NULL,
	TRANSACTION_STATUS VARCHAR(10) NOT NULL,
	-- FIXME: MerchantTransactionEntity maps this column as @Column(name="MERCHANT_ID ")
	-- with a TRAILING SPACE. The source DDL declares it (correctly) as MERCHANT_ID with
	-- no trailing space, and the entity works only because SQL ignores trailing whitespace
	-- in the unquoted generated identifier. Reconcile the entity annotation in a later phase.
	MERCHANT_ID INT(4),
	constraint EW_MERCHANT_TRANSACTION_ID_PK primary key (MERCHANT_TRANSACTION_ID)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- LEGACY redundant table: no JPA entity maps MERCHANT_TRANSACTION_MAPPING. Kept for schema
-- fidelity with the original script; the MERCHANT_TRANSACTION.MERCHANT_ID FK column supersedes it.
CREATE TABLE MERCHANT_TRANSACTION_MAPPING(
	MERCHANT_TRANSACTION_ID BIGINT(10) NOT NULL,
	MERCHANT_ID INT(4) NOT NULL
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE AW_SECURITY_QUESTION (
	QUESTION_ID BIGINT(10),
	QUESTION VARCHAR(255) UNIQUE NOT NULL,
	CONSTRAINT AW_SQ_QUESTION_ID_PK PRIMARY KEY ( QUESTION_ID )
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


ALTER TABLE WALLET_USER ADD CONSTRAINT AW_WALLET_USER_STATUS_CHK CHECK (USER_STATUS IN ('ACTIVE','INACTIVE'));
ALTER TABLE WALLET_USER ADD CONSTRAINT AW_WALLET_USER_QUESTION_ID_FK FOREIGN KEY ( SECURITY_QUESTION_ID ) REFERENCES AW_SECURITY_QUESTION( QUESTION_ID );

ALTER TABLE USER_CARD_MAPPING ADD CONSTRAINT AW_USER_CARD_EMAIL_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );
ALTER TABLE USER_CARD_MAPPING ADD CONSTRAINT AW_USER_CARD_ID_FK FOREIGN KEY ( CARD_ID ) REFERENCES CARD( CARD_ID );

ALTER TABLE CARD ADD CONSTRAINT AW_CARD_BANK_ID_FK FOREIGN KEY ( BANK_ID ) REFERENCES BANK( BANK_ID );
ALTER TABLE CARD ADD CONSTRAINT AW_CARD_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );
ALTER TABLE CARD ADD CONSTRAINT AW_CARD_STATUS_CHK CHECK (CARD_STATUS IN ('ACTIVE','INACTIVE'));

ALTER TABLE MERCHANT_SERVICE_MAPPING ADD CONSTRAINT EW_M_S_MAPPING_MERCHANT_ID_FK FOREIGN KEY ( MERCHANT_ID ) REFERENCES MERCHANT( MERCHANT_ID );
ALTER TABLE MERCHANT_SERVICE_MAPPING ADD CONSTRAINT EW_M_S_MAPPING_SERVICE_ID_FK FOREIGN KEY ( SERVICE_ID ) REFERENCES MERCHANT_SERVICE_TYPE( SERVICE_ID );

ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT AW_PAYMENT_TYPE_FROM_CHK CHECK (PAYMENT_FROM IN ('B','M','W'));
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT AW_PAYMENT_TYPE_TO_CHK CHECK (PAYMENT_TO IN ('B','M','W'));
ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT AW_PAYMENT_TYPE_CHK CHECK (PAYMENT_TYPE IN ('D','C'));

ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_USER_TXN_AMOUNT_CHK CHECK (AMOUNT > 0);
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_USER_TXN_PAYMENT_TYPE_ID_FK FOREIGN KEY ( PAYMENT_TYPE_ID ) REFERENCES PAYMENT_TYPE( PAYMENT_TYPE_ID );
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_TRXN_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );


ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_USER_TXN_STATUS_CHK CHECK (TRANSACTION_STATUS IN ('SUCCESS','FAILURE', 'PENDING'));

ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_USER_TXN_POINTS_EARNED_CHK CHECK (POINTS_EARNED >= 0);
ALTER TABLE USER_TRANSACTION ADD CONSTRAINT AW_USER_TXN_IS_REDEEMED_CHK CHECK (IS_REDEEMED IN ('Y','N'));

ALTER TABLE USER_TRANSACTION_MAPPING ADD CONSTRAINT AW_USER_TXN_MPNG_USER_ID_FK FOREIGN KEY ( USER_ID ) REFERENCES WALLET_USER( USER_ID );
ALTER TABLE USER_TRANSACTION_MAPPING ADD CONSTRAINT AW_USER_TXN_MPNG_TXN_ID_FK FOREIGN KEY ( USER_TRANSACTION_ID ) REFERENCES USER_TRANSACTION( USER_TRANSACTION_ID );

ALTER TABLE MERCHANT_TRANSACTION ADD CONSTRAINT AW_MERCHANT_TXN_AMOUNT_CHK CHECK (AMOUNT > 0);

ALTER TABLE MERCHANT_TRANSACTION ADD CONSTRAINT AW_MERCHANT_TXN_PMT_TYP_ID_FK FOREIGN KEY ( PAYMENT_TYPE_ID ) REFERENCES PAYMENT_TYPE( PAYMENT_TYPE_ID );

ALTER TABLE MERCHANT_TRANSACTION ADD CONSTRAINT AW_TXN_MERCHANT_ID_FK FOREIGN KEY ( MERCHANT_ID ) REFERENCES MERCHANT( MERCHANT_ID );

ALTER TABLE MERCHANT_TRANSACTION ADD CONSTRAINT AW_MERCHANT_TXN_STATUS_CHK CHECK (TRANSACTION_STATUS IN ('SUCCESS','FAILURE', 'PENDING'));

ALTER TABLE MERCHANT_TRANSACTION_MAPPING ADD CONSTRAINT AW_MERCHANT_TXN_MPNG_TXN_ID_FK FOREIGN KEY ( MERCHANT_TRANSACTION_ID ) REFERENCES MERCHANT_TRANSACTION( MERCHANT_TRANSACTION_ID );
ALTER TABLE MERCHANT_TRANSACTION_MAPPING ADD CONSTRAINT AW_MERCHANT_TXN_MPNG_ID_FK FOREIGN KEY ( MERCHANT_ID ) REFERENCES MERCHANT( MERCHANT_ID );
