-- Walleto bank-api schema (migrated from EDUBankMySql.sql).
-- Changes vs legacy: charset latin1 -> utf8mb4/utf8mb4_unicode_ci; money columns
-- FLOAT(12,4) -> DECIMAL(19,4); ACCOUNT gains a VERSION (optimistic-lock) column;
-- TRANSACTION gains IDEMPOTENCY_KEY and TRANSACTION_ID widened to BIGINT;
-- DEBIT_CARD.CVV removed (never stored). Column names carry no trailing spaces.
-- The drop/create/use-database header is intentionally stripped (Flyway owns the DB).

CREATE TABLE TELLER (
    TELLER_ID INT NOT NULL,
    LOGIN_NAME VARCHAR(5) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PS_TELLER_ID_PK PRIMARY KEY (TELLER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT AUTO_INCREMENT,
    EMAILID VARCHAR(255) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    SECURITY_QUESTION_ID BIGINT,
    SECURITY_ANSWER VARCHAR(100),
    CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY INT NOT NULL,
    MODIFIED_TIMESTAMP TIMESTAMP NULL DEFAULT NULL,
    MODIFIED_BY INT,
    CONSTRAINT PS_CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE CUSTOMER_LOGIN (
    CUSTOMER_LOGIN_ID INT AUTO_INCREMENT,
    LOGIN_NAME VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    LOCKED_STATUS VARCHAR(10) DEFAULT 'UNLOCKED' NOT NULL,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PS_CUSTOMER_LOGIN_ID_PK PRIMARY KEY (CUSTOMER_LOGIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE BRANCH (
    BRANCH_ID INT NOT NULL,
    IFSC VARCHAR(11) UNIQUE NOT NULL,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    BRANCH_CODE VARCHAR(6) NOT NULL,
    CONSTRAINT PS_BRANCH_ID_PK PRIMARY KEY (BRANCH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT AUTO_INCREMENT,
    ACCOUNT_NUMBER VARCHAR(15) UNIQUE NOT NULL,
    BRANCH_ID INT NOT NULL,
    BALANCE DECIMAL(19,4) NOT NULL,
    LOCKED_BALANCE DECIMAL(19,4) DEFAULT 0 NOT NULL,
    ACCOUNT_STATUS VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT PS_ACCOUNT_ID_PK PRIMARY KEY (ACCOUNT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE ACCOUNT_CUSTOMER_MAPPING (
    ACCOUNT_CUSTOMER_MAPPING_ID INT AUTO_INCREMENT,
    ACCOUNT_NUMBER VARCHAR(15) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    MAPPING_STATUS VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT PS_ACCOUNT_CUSTOMER_MAPP_ID_PK PRIMARY KEY (ACCOUNT_CUSTOMER_MAPPING_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE DEBIT_CARD (
    DEBIT_CARD_ID INT AUTO_INCREMENT,
    DEBIT_CARD_NUMBER VARCHAR(16) NOT NULL UNIQUE,
    ACCOUNT_CUSTOMER_MAPPING_ID INT NOT NULL,
    VALID_FROM DATE NOT NULL,
    VALID_THRU DATE NOT NULL,
    PIN VARCHAR(100) NOT NULL,
    LOCKED_STATUS VARCHAR(10) DEFAULT 'UNLOCKED' NOT NULL,
    DEBIT_CARD_STATUS VARCHAR(10) DEFAULT 'ACTIVE' NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY INT NOT NULL,
    MODIFIED_TIMESTAMP TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT PS_DEBIT_CARD_ID_PK PRIMARY KEY (DEBIT_CARD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TRANSACTION (
    TRANSACTION_ID BIGINT AUTO_INCREMENT,
    ACCOUNT_NUMBER VARCHAR(15) NOT NULL,
    AMOUNT DECIMAL(19,4) NOT NULL,
    TRANSACTION_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    TRANSACTION_MODE VARCHAR(20) NOT NULL,
    REMARKS VARCHAR(30),
    INFO VARCHAR(200) NOT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(80),
    CONSTRAINT PS_TRANSACTION_ID_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT UQ_TRANSACTION_IDEMPOTENCY_KEY UNIQUE (IDEMPOTENCY_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE EDUBANK_SECURITY_QUESTION (
    QUESTION_ID BIGINT AUTO_INCREMENT,
    QUESTION VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT EDU_SQ_QUESTION_ID_PK PRIMARY KEY (QUESTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
